### ISSUE TITLE
why does autoscaling instance fail health checks after seed process?

### ISSUE THREAD

**Issue by drewmullen** [appgate/sdp-tf-reference-architecture#10]
After my new gateway is seeded, it disables ssh and starts failing health status checks. 

I can specifically tell you that its the seeding process because during #8 and #9 I was ssh'd into the box trying to troubleshoot those. What happens is that I can register with the `upscale` [command with these parameters](https://github.com/appgate/sdp-tf-reference-architecture/blob/4d9c9fcf01c4f12b54050a5c3c41e872be4770ff/deployment/aws/gateways/userdata.tpl#L58), but as soon as i run `mv /tmp/seed.json /home/cz/seed.json` i get booted from my ssh session (guessing this is a security precaution, nbd) and then the instance starts failing "Instance Status Checks" (System status checks pass) then eventually the ASG recreates it

**Comment by thomascellerier** [comment]
That would be the case if you disabled SSH in your template. For the instance status checks failing logs would be useful to know what is happening.

**Comment by drewmullen** [comment]
i checked our template and im seeing ssh enabled: 
![image](https://user-images.githubusercontent.com/3812162/118985596-9433ae00-b94c-11eb-9df0-c24675bf3b84.png)

yeah i would love to provide logs (or hopefully solve myself) as soon as i can see them :D
