### ISSUE TITLE
instances built in aws should use IMDSv2

### ISSUE THREAD

**Issue by drewmullen** [appgate/sdp-tf-reference-architecture#5]
to protect against SSRF: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html

its fine to dev on IMDSv1 but best practice is v2

**Comment by thomascellerier** [comment]
Yes this makes sense :+1:.

To elaborate on this we added support for AWS IMDSv2 in 5.3.1, with additional support for the AWS resolver in 5.3.2.
So that would be need to be conditioned on the appliance version.

**Comment by danijeel** [comment]
this is fixed in the [main branch](https://github.com/appgate/sdp-tf-reference-architecture/blob/3067d4202c114bcf6996099ce76322b1489a2f66/deployment/aws/controller/data.tf#L35-L36) now.
