### ISSUE TITLE
Invalid provider ref

### ISSUE THREAD

**Issue by decta-ramsay** [appgate/sdp-tf-reference-architecture#6]
https://github.com/appgate/sdp-tf-reference-architecture/blob/c28c7db0ca6a83a7a87d0c13543aec090e0d89c5/deployment/aws/gateways/appgate.tf#L4

The host "appgate.com" given in in provider source address
"appgate.com/appgate/appgate-sdp" does not offer a Terraform provider
registry.

I suspect the provider has been moved in the rebrand?

**Comment by danijeel** [comment]
Hello @decta-ramsay,

The provider is not in the official terraform registery, so you need to download and install it manually.
In this case, "`appgate.com/appgate/appgate-sdp`" is just a namespace, not a valid url.

for terraform >= 0.13.0
you can do:
```bash
#!/usr/bin/env bash

VERSION=0.4.0
OS="linux"
PLATFORM="amd64"
mkdir -p $HOME/.terraform.d/plugins/appgate.com/appgate/appgate-sdp/${VERSION}/${OS}_${PLATFORM}

curl -Lo provider.zip https://github.com/appgate/terraform-provider-appgate-sdp/releases/download/v${VERSION}/terraform-provider-appgate-sdp_${VERSION}_${OS}_${PLATFORM}.zip
unzip provider.zip
mv terraform-provider-appgate-sdp_v$VERSION  $HOME/.terraform.d/plugins/appgate.com/appgate/appgate-sdp/${VERSION}/${OS}_${PLATFORM}/terraform-provider-appgate-sdp
```





and for terraform <= 0.12
```bash

#!/usr/bin/env bash

VERSION=0.4.0
OS="linux"
PLATFORM="amd64"
mkdir -p $HOME/.terraform.d/plugins/

curl -Lo provider.zip https://github.com/appgate/terraform-provider-appgate-sdp/releases/download/v${VERSION}/terraform-provider-appgate-sdp_${VERSION}_${OS}_${PLATFORM}.zip
unzip provider.zip
mv terraform-provider-appgate-sdp_v$VERSION  $HOME/.terraform.d/plugins/
```

**Comment by decta-ramsay** [comment]
ahh fair enough I thought you where hosting the binary
