### ISSUE TITLE
secrets manager password extraction fails in python script

### ISSUE THREAD

**Issue by drewmullen** [appgate/sdp-tf-reference-architecture#9]
`secret_string = json.loads(stdout.decode())['SecretString']` this only extracts a string of the blob:
```
$ /tmp/password-executable
{"password": "{\"myuser\":\"mypassword\"}"}
```

you can use a 2nd json.loads then cast to a list to extract:
`secret_string = list(json.loads(json.loads(stdout.decode())['SecretString']).values())[0]`

**Comment by thomascellerier** [comment]
The script here is just an example, it depends the kind of payload you store in secrets manager. If your secret string is using json then you need another layer of decoding, but that is not necessarily the case here.

**Comment by drewmullen** [comment]
TIL, ty
future person reading this: use `plaintext` option for your secrets manager password and only place your string, no `"`, no `{`

OR change the script to match your
